### ISSUE TITLE
Icon 行报错, Python 2.7

### ISSUE THREAD

**Issue by HisenZhang** [airob0t/idcardgenerator#1]
这一行关于icon的会报错
root.iconbitmap(os.path.join(base_dir, 'ico.ico'))
--------
Traceback (most recent call last):
  File "idcardgenerator.py", line 156, in <module>
    root.iconbitmap(os.path.join(base_dir, 'ico.ico'))
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1702, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "usedres/ico.ico" not defined

--------
目前的解决方法是注释掉....

**Comment by airob0t** [comment]
此方法要求文件在同一目录，由于更改过资源文件路径导致出错。这行代码是设置图标，不影响，可以注释掉。
